#!/usr/bin/env bash

function assert_equal() {
  [[ "$#" -ne 2 ]] && echo "${FUNCNAME} must receive two arguments, received $#" && exit 1
  command=$1
  expected=$2


  output=$(eval $command)
  if [ "${output}" == "${expected}" ]; then
    printf "%-50s \U2713\n" "$command" 
  else
    printf "%-50s \U2717\n" "$command" 
    printf "%-10s: %s\n%-10s: %s\n" "output" "${output}" "expected" "${expected}"
    return 1
  fi
}
