#!/usr/bin/env bash

SRC_PATH=$(dirname -- "${BASH_SOURCE[0]}")

REPO_PATH="${SRC_PATH}/.."
if [ -n "$1" ]; then
  REPO_PATH="$1"
fi

. $SRC_PATH/check


PATH=$PATH:$SRC_PATH/../bin

BASE=afb39f
SECOND=f06107

assert_equal "gitits -s -b ${BASE} -r ${SECOND} -m renato ${REPO_PATH}" "renato 1 1 0"

assert_equal "gitits -s -b ${SECOND} -r ${SECOND} -m renato ${REPO_PATH}" "renato 1 1 0"

# multiline output
expected="aeliton 62 0 62
renato 1 1 0"
assert_equal "gitits -s -r ${SECOND} ${REPO_PATH}" "${expected}"
