name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clone
        run: git clone https://github.com/aeliton/gitits.git $GITHUB_WORKSPACE/gitits_clone

      - name: run tests
        run: $GITHUB_WORKSPACE/test/test_gitits $GITHUB_WORKSPACE/gitits_clone
